apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
     app: mongodb
     project: roboshop
     teir: db

spec:
  replicas: 1
  selector:
    matchLabels:
        app: mongodb
        project: roboshop
        teir: db
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        teir: db
    spec:
      containers:
      - name: mongodb
        image: awsmouli/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
     app: mongodb
     project: roboshop
     teir: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017


        