apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data: 
   MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
     app: user
     project: roboshop
     teir: app

spec:
  replicas: 1
  selector:
    matchLabels:
        app: user
        project: roboshop
        teir: app
  template:
    metadata:
      labels:
        app: user
        project: roboshop
        teir: app
    spec:
      containers:
      - name: user
        image: awsmouli/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
     app: user
     project: roboshop
     teir: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


        