apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
     app: web
     project: roboshop
     teir: web

spec:
  replicas: 1
  selector:
    matchLabels:
        app: web
        project: roboshop
        teir: web
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        teir: web
    spec:
      containers:
      - name: web
        image: awsmouli/web:v1
        imagePullPolicy: Always
        

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
     app: web
     project: roboshop
     teir: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


        